apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap-restapi
data:
  restapi.yaml: |
    address: "0.0.0.0:8080"
    uiAddress: "https://bakshi41c.github.io/synthetic-heart-ui?server=http://localhost:8080&cluster=local&promUrl=localhost:9090"
    storageAddress: "redis.{{ .Release.Namespace }}.svc:6379"