---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - synheart.infra.webex.com
  resources:
  - synthetictests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - synheart.infra.webex.com
  resources:
  - synthetictests/status
  verbs:
  - get
  - patch
  - update
