# Values for synthetic heart chart
# Values for controller
controller:
  logLevel: INFO
  image:
    repository: bakshi41c/synheart-controller
    tag: "v1.2.0-dev20"
    pullPolicy: IfNotPresent
  ports:
    - containerPort: 2112 # For prometheus
      protocol: TCP
  agentStatusDeadline: 60s  # How long before an agent is considered dead if no status is posted (should be > agent.exportRate)
  annotations:
    prometheus.io/port: "2112"
    prometheus.io/scrape: "true"
  securityContext:
    capabilities:
      drop:
        - all
    runAsUser: 65534
    runAsNonRoot: true
    readOnlyRootFilesystem: true

# Values for agents
agent:
  replicaCount: 6
  logLevel: INFO
  printPluginLogs: onFail   # Whether to print logs of test runs (always, onFail, never)
  exportRate: 15s           # How often to export health status of plugins/agent
  image:
    repository: bakshi41c/synheart-agent
    tag: "v1.2.0-dev20"
    pullPolicy: IfNotPresent
  ports:
    - containerPort: 2112 # For prometheus
      protocol: TCP
  configMapFiles: {}
  annotations:
    prometheus.io/port: "2112"
    prometheus.io/scrape: "true"
  resources:
    limits:
      cpu: "100m"
      memory: "512Mi"
    requests:
      cpu: "50m"
      memory: "64Mi"
  securityContext:
    capabilities:
      drop:
        - all
    runAsUser: 65534
    runAsNonRoot: true
    readOnlyRootFilesystem: true
  debugMode: false
  labels:
    synheart.infra.webex.com/discover: "true"

# Values for restapi
restapi:
  logLevel: INFO
  image:
    repository: bakshi41c/synheart-restapi
    tag: "v1.2.0-dev20"
    pullPolicy: IfNotPresent
  annotations: {}
  ports:
    - containerPort: 8080
      protocol: TCP
  securityContext:
    capabilities:
      drop:
        - all
    runAsUser: 65534
    runAsNonRoot: true
    readOnlyRootFilesystem: true
  certificateIssuer: letsencrypt-prod

priorityClassName: system-cluster-critical
tolerations:
  - operator: Exists
nodeSelector:
  kubernetes.io/os: linux

# Values for Redis cluster
redis:
  image:
    repository: redis
    tag: 7.2-alpine3.20
    pullPolicy: IfNotPresent
