
############################
# Build a image based on synthetic-heart
############################
FROM localhost/synheart-agent:dev-latest

# Copy over python plugins
COPY ./agent/plugins/syntests-python/ /app/synthetic-heart/plugins-python

# Install Python
ENV PYTHONUNBUFFERED=1
RUN apk add --update --no-cache python3 py3-pip git
RUN pip3 install --no-cache --upgrade pip setuptools --break-system-packages
RUN cd /app/synthetic-heart/plugins-python && sh install_requirements.sh --break-system-packages
