############################
# STEP 1 build the image for creating the executable
############################
FROM docker.io/library/golang:1.22-alpine3.19 as builder

# Install git + SSL ca certificates + make
RUN apk update && apk upgrade && apk add --no-cache git ca-certificates make unzip g++ && update-ca-certificates && apk --no-cache add openssl wget && rm -rf /var/cache/apk/*

# Create appuser
RUN adduser -D -g '' appuser

# Install protoc
RUN wget https://github.com/protocolbuffers/protobuf/releases/download/v3.20.1/protoc-3.20.1-linux-x86_64.zip
RUN unzip protoc-3.20.1-linux-x86_64.zip
RUN cp ./bin/protoc /usr/local/bin/protoc
RUN cp -a ./include/. /usr/local/include/

# Install GRPC golang-plugin for protoc
RUN go install github.com/golang/protobuf/protoc-gen-go@v1.5.2

WORKDIR /app

COPY agent/go.mod agent/.
COPY agent/go.sum agent/.
COPY common/go.mod common/.
COPY common/go.sum common/.
RUN cd agent && go mod download

COPY . .

# Build the binary
RUN mkdir -p /app/synthetic-heart/
RUN touch /app/synthetic-heart/.emptyfile

# Compile the binary
RUN cd agent/ && make build-agent-only

RUN mv agent/bin/* /app/synthetic-heart
RUN mkdir /app/synthetic-heart/plugins

############################
# STEP 2 build a small image with only the executable
############################
FROM docker.io/library/alpine:3.19

# Copy our static executables
COPY --from=builder /app/synthetic-heart /app/synthetic-heart

# Create a /tmp/ diretctory (required for go plugin for Unix Domain Socket)
COPY --from=builder /app/synthetic-heart/.emptyfile /tmp/.emptyfile

WORKDIR /app/synthetic-heart

# Run the binary.
ENTRYPOINT ["./agent"]

