name: py-test
labels:
  foo: bar
namespace: test-ns-01
pluginName: json-ping.py
node: "*"
displayName: Test Python Plugin
description: Test to check the python plugin
timeouts:
  run: 1m
repeat: 20s
config: |-
  url: https://api64.ipify.org/?format=json
  queries:
    - query: "ip"
      expected: "^\\d+\\.\\d+\\.\\d+\\.\\d+$"
    - query: "ip"
      expected: "^\\d+\\.\\d+\\.\\d+\\.\\d+.\\d+$"